repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: mixed-line-ending

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: remove-crlf

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v21.1.0  # Use the sha / tag you want to point at
    hooks:
      - id: clang-format
        verbose: true
